export type TTemp = {
	id: string
	title: string
	xp: number
	description: string
	category: string
	duration: string
	difficulty: string
	streak_goal: number
	total_uses: number
}

const temp: TTemp[] = [
	{
		category: "fitness",
		description: "Do at least 30 minutes of exercise.",
		difficulty: "hard",
		duration: "daily",
		id: "exercise",
		streak_goal: 5,
		title: "Exercise",
		total_uses: 0,
		xp: 50,
	},
	{
		category: "personal growth",
		description: "Read for at least 20 minutes.",
		difficulty: "medium",
		duration: "daily",
		id: "read_book",
		streak_goal: 3,
		title: "Read a Book",
		total_uses: 0,
		xp: 30,
	},
	{
		category: "mental health",
		description: "Write down your thoughts for at least 5 minutes.",
		difficulty: "easy",
		duration: "daily",
		id: "journal",
		streak_goal: 3,
		title: "Journal",
		total_uses: 0,
		xp: 20,
	},
	{
		category: "fitness",
		description: "Take a 15-minute walk outside.",
		difficulty: "easy",
		duration: "daily",
		id: "walk",
		streak_goal: 5,
		title: "Go for a Walk",
		total_uses: 0,
		xp: 25,
	},
	{
		category: "health",
		description: "Drink at least 8 glasses of water today.",
		difficulty: "easy",
		duration: "daily",
		id: "drink_water",
		streak_goal: 7,
		title: "Drink Water",
		total_uses: 0,
		xp: 20,
	},
	{
		category: "fitness",
		description: "Do a 10-minute stretching routine.",
		difficulty: "easy",
		duration: "daily",
		id: "stretching",
		streak_goal: 5,
		title: "Stretching",
		total_uses: 0,
		xp: 25,
	},
	{
		category: "health",
		description: "Go to bed before 10 PM.",
		difficulty: "medium",
		duration: "daily",
		id: "sleep_early",
		streak_goal: 3,
		title: "Sleep Early",
		total_uses: 0,
		xp: 30,
	},
	{
		category: "personal growth",
		description: "Spend at least 15 minutes learning a new skill.",
		difficulty: "medium",
		duration: "daily",
		id: "learn_something",
		streak_goal: 3,
		title: "Learn Something New",
		total_uses: 0,
		xp: 30,
	},
	{
		category: "mental health",
		description: "Write down three things you’re grateful for.",
		difficulty: "easy",
		duration: "daily",
		id: "gratitude",
		streak_goal: 3,
		title: "Express Gratitude",
		total_uses: 0,
		xp: 20,
	},
	{
		category: "personal growth",
		description: "Avoid screens for at least 1 hour before bed.",
		difficulty: "medium",
		duration: "daily",
		id: "limit_screen",
		streak_goal: 3,
		title: "Limit Screen Time",
		total_uses: 0,
		xp: 30,
	},
	{
		category: "mental health",
		description: "Practice deep breathing for 5 minutes.",
		difficulty: "easy",
		duration: "daily",
		id: "deep_breathing",
		streak_goal: 3,
		title: "Deep Breathing",
		total_uses: 0,
		xp: 20,
	},
	{
		category: "social",
		description: "Send a kind message to a friend or loved one.",
		difficulty: "easy",
		duration: "daily",
		id: "kind_message",
		streak_goal: 3,
		title: "Send a Kind Message",
		total_uses: 0,
		xp: 20,
	},
	{
		category: "nutrition",
		description: "Eat at least one serving of fruits or vegetables.",
		difficulty: "easy",
		duration: "daily",
		id: "eat_healthy",
		streak_goal: 5,
		title: "Eat Healthy",
		total_uses: 0,
		xp: 25,
	},
	{
		category: "fitness",
		description: "Do 20 push-ups or sit-ups.",
		difficulty: "medium",
		duration: "daily",
		id: "pushups",
		streak_goal: 3,
		title: "Push-ups/Sit-ups",
		total_uses: 0,
		xp: 30,
	},
	{
		category: "personal growth",
		description: "Learn five new words in a different language.",
		difficulty: "medium",
		duration: "daily",
		id: "learn_language",
		streak_goal: 3,
		title: "Learn a Language",
		total_uses: 0,
		xp: 30,
	},
	{
		category: "mental health",
		description: "Spend 10 minutes outside in fresh air.",
		difficulty: "easy",
		duration: "daily",
		id: "fresh_air",
		streak_goal: 3,
		title: "Get Fresh Air",
		total_uses: 0,
		xp: 20,
	},
	{
		category: "organization",
		description: "Declutter or clean for 10 minutes.",
		difficulty: "easy",
		duration: "daily",
		id: "declutter",
		streak_goal: 3,
		title: "Declutter",
		total_uses: 0,
		xp: 20,
	},
	{
		category: "social",
		description: "Have a meaningful conversation with someone.",
		difficulty: "medium",
		duration: "daily",
		id: "conversation",
		streak_goal: 3,
		title: "Meaningful Conversation",
		total_uses: 0,
		xp: 30,
	},
	{
		category: "personal growth",
		description: "Spend 10 minutes reflecting on your goals.",
		difficulty: "medium",
		duration: "daily",
		id: "goal_reflection",
		streak_goal: 3,
		title: "Reflect on Goals",
		total_uses: 0,
		xp: 30,
	},
]

export default temp
